apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      version: green
  template:
    metadata:
      labels:
        app: nodejs-app
        version: green
    spec:
      containers:
        - name: nodejs-app
          image: shahebaz/nodejs-app:latest
          ports:
            - containerPort: 8080
