apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nodejs
spec:
  host: nodejs
  subsets:
  - name: blue
    labels:
      version: blue
  - name: green
    labels:
      version: green
