apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nodejs-app
  namespace: allianz-blue-green
spec:
  host: nodejs-app
  subsets:
    - name: blue
      labels:
        version: blue
    - name: green
      labels:
        version: green
