apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nodejs-app
spec:
  hosts:
    - "*"   # Accept any host (localhost or custom)
  gateways:
    - istio-ingressgateway   # Attach to Ingress Gateway (not mesh)
  http:
    - route:
        - destination:
            host: nodejs-app
            subset: blue
          weight: 90
        - destination:
            host: nodejs-app
            subset: green
          weight: 10
