apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: allianz-blue-green
  # Name of the Role
  name: jenkins-deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
