apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins  # Add the namespace here
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080  # Internal port Jenkins runs on
      targetPort: 8080  # Port inside the container
      nodePort: 30000  # The port on the Minikube node

